version: "3.9"

services:
  backend:
    build: ./job-search-backend
    container_name: job-search-backend
    environment:
      - Adzuna__AppId=${ADZUNA_APP_ID}
      - Adzuna__AppKey=${ADZUNA_APP_KEY}
      - FRONTEND_URL=http://frontend
      - API_KEY=${API_KEY}
    ports:
      - "5000:80"
        
  frontend:
    build: ./job-search-frontend
    container_name: job-search-frontend
    ports:
      - "3000:80"
    depends_on:
      - job-search-backend