services:
  backend:
    build:
      context: .
      dockerfile: ./job-search-backend/Dockerfile
    container_name: job-search-backend
    environment:
      - Adzuna__AppId=${ADZUNA_APP_ID}
      - Adzuna__AppKey=${ADZUNA_APP_KEY}
      - FRONTEND_URL=http://frontend
      - API_KEY=${API_KEY}
    ports:
      - "5080:8080"
        
  frontend:
    build: 
      context: ./job-search-frontend
      dockerfile: Dockerfile
    container_name: job-search-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend